[project]
name = "eventcamera"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "issaiass", email = "issaiass@hotmail.com" }
]
requires-python = ">=3.11"
dependencies = [
    "numpy>=2.5.1",
    "opencv-python-headless>=5.0.0.93",
]

[project.scripts]
eventcamera = "eventcamera:main"

[dependency-groups]
dev = [
    "black>=24.0.0",
    "mypy>=1.10.0",
    "pylint>=3.2.0",
    "pytest>=8.0.0",
    "pytest-cov>=5.0.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
